/**
 * generate-ascii.ts — rasterize resolved SVGs into ASCII and emit game data.
 *
 * Reads scripts/svg/<id>.svg + scripts/.cache/provenance.json, produces the
 * five ASCII variants per logo (clean/glitched/cropped/lowRes/revealStages),
 * and writes src/data/logos.generated.ts. Deterministic: the seed is the logo
 * id, so ASCII is stable across builds.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { LOGO_SOURCES } from "../src/data/logoSources"
import type { AsciiVariants, LogoEntry } from "../src/types/logo"
import { cropLines, glitchLines, padLines } from "../src/utils/asciiTransform"
import { svgToAsciiLines } from "./lib/svgToAscii"
import type { Provenance } from "./fetch-icons"

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, "..")
const SVG_DIR = join(HERE, "svg")
const CACHE = join(HERE, ".cache", "provenance.json")
const OUT = join(ROOT, "src", "data", "logos.generated.ts")

const loadProvenance = (): Map<string, Provenance> => {
  if (!existsSync(CACHE)) return new Map()
  const list = JSON.parse(readFileSync(CACHE, "utf8")) as Provenance[]
  return new Map(list.map((p) => [p.id, p]))
}

// Only the variants the app actually renders: clean (Hangman + Trivia easy),
// glitched (Trivia medium/expert), cropped (Trivia hard). The old lowRes /
// revealStages frames are no longer emitted to keep the bundle small.
const buildVariants = (clean: string[], seed: string): AsciiVariants => {
  const padded = padLines(clean)
  return {
    clean: padded,
    glitched: glitchLines(padded, 0.2, `${seed}:g`),
    cropped: cropLines(padded, 0.62),
  }
}

const main = async (): Promise<void> => {
  const provenance = loadProvenance()
  const entries: LogoEntry[] = []

  for (const source of LOGO_SOURCES) {
    const svgPath = join(SVG_DIR, `${source.id}.svg`)
    if (!existsSync(svgPath)) {
      console.warn(`  ✗ ${source.id}: missing SVG (run fetch-icons first)`)
      continue
    }
    const svg = readFileSync(svgPath)
    const clean = await svgToAsciiLines(svg, source.difficulty)
    const ascii = buildVariants(clean, source.id)
    const prov = provenance.get(source.id)

    entries.push({
      id: source.id,
      name: source.name,
      aliases: source.aliases,
      category: source.category,
      difficulty: source.difficulty,
      tags: source.tags,
      ascii,
      hints: source.hints,
      source: prov
        ? {
            provider: prov.provider,
            slug: prov.slug,
            variant: prov.variant,
            license: prov.license,
            trademarkNote: prov.trademarkNote,
          }
        : undefined,
    })
    console.log(`  ✓ ${source.id.padEnd(16)} ${clean.length} rows`)
  }

  const header = `import type { LogoEntry } from "../types/logo"

/**
 * AUTO-GENERATED by scripts/generate-ascii.ts. Do not edit by hand.
 * Regenerate with: npm run assets
 */
export const GENERATED_LOGOS: LogoEntry[] = `

  writeFileSync(OUT, header + JSON.stringify(entries, null, 2) + "\n", "utf8")
  console.log(`\nWrote ${entries.length} logos to ${OUT}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
